# Generated by Django 3.0.5 on 2020-04-13 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ig.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_data_id', models.CharField(default=ig.models.increment_computation_data_number, editable=False, max_length=6)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computation_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
