# Generated by Django 3.0.5 on 2020-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0005_auto_20200419_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='computationdata',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identificationnumber',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterlist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ssn',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
