# Generated by Django 3.0.5 on 2020-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0008_auto_20200419_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='revision',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N')], default=None, max_length=1, null=True),
        ),
    ]
