# Generated by Django 3.0.5 on 2020-07-10 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ig.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ig', '0012_auto_20200420_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='QInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_inquiry_id', models.CharField(default=ig.models.increment_q_inquiry_number, editable=False, max_length=6)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('revision', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N')], default=None, max_length=1, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qinquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
