# Generated by Django 3.0.5 on 2020-07-13 15:06

from django.db import migrations, models
import ig.models


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0013_qinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qinquiry',
            name='q_inquiry_id',
            field=models.CharField(default=ig.models.increment_q_inquiry_number, editable=False, max_length=7),
        ),
    ]
